### ISSUE TITLE
Remove action

### ISSUE THREAD

**Issue by silentlight** [revolver-app/vuex-orm#11]
Hello,

Great job on this package. It really looks promising.

One thing that I've been looking for is ability to remove item. How can I do that?

**Comment by kiaking** [comment]
Hi, thank you for checking out Vuex ORM!

Remove feature is not implemented just yet! And Yes, I'm going to add it soon.

Meanwhile, you could do something like below to remove items from the store.

```js
// Get all data.
const items = store.getters['entities/items/all']()

// Filter items to remove any. Below example will remove an item which has id of 3.
const data = items.filter(item => item.id !== 3)

// Save filtered data to the store.
store.dispatch('entities/items/create', { data })


// In one shot.
store.dispatch('entities/items/create', {
  data: store.getters['entities/items/all']().filter(item => item.id !== 3)
})
```

**Comment by silentlight** [comment]
Great.

Thank you for your hint!

**Comment by kiaking** [comment]
@silentlight I've added the feature! Once I release next version, you'll be able do `store.dispatch('entities/users/delete', 1)` to remove data from the store.

**Comment by kiaking** [comment]
Now `delete` action is available at Vuex ORM 0.11.0 and it's released! [Doc is here](https://revolver-app.gitbooks.io/vuex-orm/store/deleting-data.html).

**Comment by CinKon** [comment]
It would be nice to delete ALL entities at once :)

**Comment by kiaking** [comment]
@CinKon Hah, indeed. I don't know why I never thought about that. I'll add that feature!

For now, you can achieve same by passing empty array to the `create` action (but I think delete all feature is more intuitive).

```js
store.dispatch('entities/users/create', { data: [] })
```

Wondering how API should look. Maybe delete method without payload...?

```js
// Delete user with id of 1.
store.dispatch('entities/users/delete, 1)

// Delete all.
store.dispatch('entities/users/delete')
```

**Comment by kiaking** [comment]
@CinKon Oh by the way, when you say "delete ALL entities" do you mean to delete all existing entities data (For example not only users but posts, comments or any entities that are registered to the database)?
