### ISSUE TITLE
hasMany relationship returns null instead of ids

### ISSUE THREAD

**Issue by silentlight** [revolver-app/vuex-orm#13]
Hi again,

I am using hasMany relationship on my model like so:

```
export default class App extends Model {
  static entity = 'apps';

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(''),
      machine_name: this.attr(''),
      version: this.attr(''),
      status: this.attr(''),
      roles: this.hasMany(Role, 'app_id'),
    };
  }
}

```

When I `Insert` apps it all works as expected. I see my apps and roles in the store and each app has array of role ids under `roles` attribute.

The problem is when I try to query all apps. 
I use `this.$store.getters['entities/apps/all']()` to get all my apps. All is good but each app has `roles` parameter set to `null` instead of array of ids. Am I missing something?

**Comment by kiaking** [comment]
Hi @silentlight 

You need to use `with` method to query relationship together with app. Could you try below code?

```js
this.$store.getters['entities/apps/query']().with('roles').get()
```

Doc: https://revolver-app.gitbooks.io/vuex-orm/store/retrieving-data.html#load-relationship

**Comment by silentlight** [comment]
@kiaking This works as expected. Thanks :)

**Comment by kiaking** [comment]
Glad I could help! Don't hesitate to open another issue if you have any other questions 😃
