### ISSUE TITLE
Add delete all feature

### ISSUE THREAD

**Issue by kiaking** [revolver-app/vuex-orm#24]
Raised from #11.

**Comment by mastermunj** [comment]
Came across need for this. On logout, I'd like to delete all entities at once.

As of now it's tedious to delete each type of entity one by one.

**Comment by CinKon** [comment]
See https://github.com/revolver-app/vuex-orm/issues/11#issuecomment-346917375

**Comment by mastermunj** [comment]
That works for only one type of entity, whereas I need single call to delete data from all defined entities.

**Comment by kiaking** [comment]
Hi all,
Thanks for your feedback!

> Came across need for this. On logout, I'd like to delete all entities at once.

This sounds very valid use case. I was wondering if needed that feature or not but yeah lets add this. I'll work on this issue and make sure it will be implemented.

**Comment by mastermunj** [comment]
Created PR #28 with possible fix.

**Comment by kiaking** [comment]
Thanks to @mastermunj, this feature is available at Vuex ORM 0.13.0 🎉 

You can now use;

```js
// Delete all data for an entity
store.dispatch('entities/users/deleteAll')

// Delete all data for all entities
store.dispatch('entities/deleteAll')
```

**Comment by kremda** [comment]
Hey, I could not find any information about:

`store.dispatch('entities/deleteAll')`

in the documentation. I think it should be added to [delete-all-data page](https://vuex-orm.github.io/vuex-orm/guide/data/deleting.html#delete-all-data )

**Comment by kiaking** [comment]
hank you for the report! Yeah, you're right! We should have that! I'll create a new issue for that.
