### ISSUE TITLE
`where` with relation-condition?

### ISSUE THREAD

**Issue by CinKon** [revolver-app/vuex-orm#32]
Is it possible, to set a `where`-condition for relationships?
Your documentation covers the case to filter the relationship-elements, but i want to filter the main-element depending wether at least one relationship-element exists or not.

Here's an example:

`user.js:`
```javascript
import { Model } from 'vuex-orm'
import Absence from './absence'

export default class User extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'user'

  static primaryKey = 'id'

  static fields () {
    return {
      id: this.attr(null),
      username: this.attr(''),
      absences: this.hasMany(Absence, 'userId')
    }
  }
}
```

`absence.js:`
```javascript
import { Model } from 'vuex-orm'

export default class Absence extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'absence'

  static primaryKey = 'id'

  static fields () {
    return {
      id: this.attr(null),
      userId: this.attr(null),
      beginning: this.attr(null),
      end: this.attr(null),
      reason: this.attr('')
    }
  }
}
```

`modules/user.js:`

```javascript
export default {
  getters: {
    absentUsers: (state, getters) => 
        getters['entities/user/query']()
          .with('absences')
          .where('absences', ???)
          .get()
  }
}
```

**Comment by kiaking** [comment]
Unfortunately no... You cannot use where clause with relationship fields right now. To achieve the desired result, you must filter through the result of the query (not sure if I can call this "workaround" though...).

But this should be able and we should add this feature. I'm thinking to add `has` method to do this.

```js
// Fetch all users with at least one Absence.
store.getters['entities/user/query']().has('absences').get()

// Maybe inverse too. Get all users without Absence.
store.getters['entities/user/query']().doesntHave('absences').get()

// For more complex query, use closure. Fetch all users with Absence containing reason of foo.
store.getters['entities/user/query']().has('absences', (query) => {
  query.where('reason', 'foo')
}).get()
```

**Comment by CinKon** [comment]
I would suggest `has` and `hasNot`.
`doesntHave` sounds pretty unfamiliar to me for cases like this.

**Comment by CinKon** [comment]
But let's think a little more forward with this:
Could it be possible, to extend the `has`-Method?
Like I could say something like "has more than 2 absences" or something.

I think conditions like this COULD be very complex, if the system allows it. For sure you could always filter the results afterwards...

**Comment by kiaking** [comment]
> I would suggest has and hasNot.

Fair enough. Lets go with `hasNot` then.

> Like I could say something like "has more than 2 absences" or something.

Nice idea. To do this, how about following idea.

First we'll implement aggregate methods such as `count`, `max`. Then use that method in the closure.

```js
// Return boolean inside closure. Below example gets users with at least 2 absences.
store.getters['entities/user/query']().has('absences', (query) => {
  return query.count() >= 2
}).get()

// Or more complex one.
store.getters['entities/user/query']().has('absences', (query) => {
  return query.where('reason', 'foo').count() >= 2
}).get()
```

So the internal logic is; if the closure returns true, then fetch that user. 

Else if closure returns query object, execute that query and if the result is not empty, then treat them as true.

```js
store.getters['entities/user/query']().has('absences', (query) => {
  return query.where('reason', 'foo')
}).get()
```

With this approach, I think the system would be fairly simple because all we need to do is to execute query and find out if the result is truthy or not.

To take this further, we could do something like this too (this is I think complex so it should be next step I guess).

```js
// Get users with 2 absences.
store.getters['entities/user/query']().has('absences', 2).get()

// Get users with more than 2 absences.
store.getters['entities/user/query']().has('absences', '>', 2).get()

// Get users with less or exactly 5 absences.
store.getters['entities/user/query']().has('absences', '<=', 5).get()
```

What do you think?

**Comment by CinKon** [comment]
Your last suggestion would strip down the code, but i don't think this is really necessary.

**Comment by kiaking** [comment]
Great. So lets implement the closure pattern first, and then maybe the shorthand one (the last suggestion). 😃

**Comment by kiaking** [comment]
This feature is now possible with Vuex ORM 0.14.0!

I've implemented the string operator as well. Please read docs for more detail.  
https://revolver-app.gitbooks.io/vuex-orm/store/retrieving-data.html#querying-relationship-existence

**Comment by ivan006** [comment]
Where can I find the docs on "hasNot" and "has" etc? I see none :')
EDIT:
Ahhh i see it doesnt yet exist 
> I'm thinking to add has method
