### ISSUE TITLE
Static property in example, vs static method getter.

### ISSUE THREAD

**Issue by EnglishAdam** [revolver-app/vuex-orm#42]
Hi,

In your [GitBook example](https://revolver-app.gitbooks.io/vuex-orm/content/getting-started.html) you use a static class property to identify the entity:

``` javascript
export default class User extends Model {
        static entity = 'users'

        static fields () { ... }
}
```

This may not be recognized in most JS environments/linters/post-processors and throw an exception. It may be worth defining it as a static getter, via the static method:

``` javascript
export default class User extends Model {
        static get entity () {
                return 'users'
        }

        static fields () { ... }
}
```
Kind regards,
Adam

**Comment by kiaking** [comment]
You have a good point! I was used to using static property, but it needs babel-preset-stage-2. Thank you for pointing out.

Yes, it's totally OK to define it as a getter, but I could make static function work too.

```js
class User extends Model {
  static entity () {
    return 'users'
  }
}
```

Just my personal opinion, but I think the simple method is more common use case than getter, maybe.

So I would like to make Vuex ORM able to treat both static property and method, so user can choose whichever they like. Then document all three available patterns (property, getter, and method).

For instance, [Redux ORM](https://github.com/tommikaikkonen/redux-orm#declare-your-models) tells a user to specify static method out side of the class.

```js
class Book extends Model {
    toString() {
        return `Book: ${this.name}`;
    }
    // Declare any static or instance methods you need.
}
Book.modelName = 'Book';
```

It's essentially the same as specifying a static property, but I don't like this syntax. I prefer your getter approach much more.

**Comment by kiaking** [comment]
Oh wait, we have `static primaryKey` too. Hm...

It is kinda pain to enable every single property as a function... So maybe documenting various option might be enough.

**Comment by kiaking** [comment]
@EnglishAdam I've added note on the doc at #43. Does this make sense to you? If this is all we need, I think I can merge it and close this issue 🎸

**Comment by kiaking** [comment]
Thank you so much for the confirmation! There's nothing wrong with defining property as a getter.

I'll merge the PR and close this issue. Please feel free to open another issue if you find anything else I can do to make docs better!

Again, thank you for the feedback ❤️
