### ISSUE TITLE
[Discussion] Vuex-Orm took the job of vuex managing state and mutations. Where should I put my actions?

### ISSUE THREAD

**Issue by cdrandin** [revolver-app/vuex-orm#431]
Originally, I had vuex modules which deal with specific parts of an API. Now using vuex-orm it has pretty much taken a large part of the responsibility from vuex. 

Should I still leave my actions in the module? Would it be best to put them in components with the lifecycle hooks (created/mounted/asyncData(nuxt))?

This seems more of a personal preference kind of thing to me, but just wondering what other peoples' thoughts are on this.

**Comment by kiaking** [comment]
@cdrandin Hi! Thank you for the feedback.

As you mentioned, it's up to developers preference, but in my case, I use both actions and Vuex ORM models to interact with the Store.

For API that relates to Model, I usually put that API logic in Model methods. For other states that are not really data, for example, is sidebar open, I use plain Vuex Actions to control them. And I execute those actions within created/mounted/asyncData/etc.

**Comment by kiaking** [comment]
Your welcome! Glad I could help. Please let us know if there's anything : )
