### ISSUE TITLE
Documentation 404 on all links

### ISSUE THREAD

**Issue by lartheon** [revolver-app/vuex-orm#750]
#### Describe the bug

Links to all the docs 404 - https://github.com/vuex-orm/vuex-orm/tree/master/docs

#### Steps to reproduce the bug

1. visit https://github.com/vuex-orm/vuex-orm/tree/master/docs
2. click any of the links in the table of contents
3. see error 404 page not found

#### Expected behaviour

Should not 404, should open the correct page

#### Versions

Master

#### Link to minimal reproduction

https://github.com/vuex-orm/vuex-orm/tree/master/docs

**Comment by cuebit** [comment]
Docs are run in vuepress and not suitable for repository browsing. As such, they can be found [here](https://vuex-orm.org/) and [here](https://next.vuex-orm.org/) 👍
