### ISSUE TITLE
I can't define relation belongsToMany

### ISSUE THREAD

**Issue by sarmancoderr** [revolver-app/vuex-orm#760]
#### Describe the bug

I have two models linked by a bridge table and I got the error `this.relation(...).localKey is not a function`

#### Steps to reproduce the bug

1. Define models [...]

Modelo **File**:
```
import { Model } from '@vuex-orm/core'
import FileTag from './FileTag'
import Tag from './Tag'

export default class File extends Model {
    static entity = 'files'

    static fields () {
        return {
            id: this.attr(null),
            path: this.string(),
        }
    }
}
```
Modelo **Tag**:
```
import { Model } from '@vuex-orm/core'
import FileTag from './FileTag'

export default class Tag extends Model {
    static entity = 'tags'

    static fields () {
        return {
            id: this.attr(null),
            name: this.string(),
            files: this.belongsToMany(File, FileTag, 'tag_id', 'file_id')
        }
    }
}

```
Modelo **FileTag**:
```
const { Model } = require('@vuex-orm/core')

export default class FileTag extends Model {
    static entity = 'file_tag'

    static primaryKey = ['file_id', 'tag_id']

    static fileds () {
        return {
            file_id: this.attr(),
            tag_id: this.attr()
        }
    }
}

```
2. Create data [...]
```
await File.create({
    data: {
        path: '/home/sarmancoder/notes.txt',
        tags: [
            { name: 'firsttag' }
        ]
    }
})
```
3. Retrieve data [...]
No data is retrieved
`this.relation(...).localKey is not a function`

#### Expected behaviour

To watch the file with the tags created, however this throws an error...

#### Versions

- Vuex ORM: 0.36.4
- nuxt 2.15.8 (in the package.json there is no vue dependency...)

#### Link to minimal reproduction

[Here is the branch where I have the error and where I am testing VuexORM](https://github.com/sarmancoderr/filetagging/tree/vuexorm)

**Comment by cuebit** [comment]
Looks like you’re creating a relation that requires primary keys at both ends, without actually providing any keys. 

If you can’t issue primary keys to reference in the join table, consider having `File` and `Tag` primary keys as `uid` fields, not generic `attr` fields.

**Comment by sarmancoderr** [comment]
The problem was that in the Tag model File not was an ORM class...
