### ISSUE TITLE
Issue with Nuxt 2

### ISSUE THREAD

**Issue by Pok09** [revolver-app/vuex-orm#771]
Hi,
Recently the installation of vuex-orm no longer works with nuxt 2, dependency problem

nuxt: ^2.15.8,
vue: ^2.6.14,

npm install @vuex-orm/core --save

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: erp@1.0.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR! vue@"^2.6.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.2" from vuex@4.0.2
npm ERR! node_modules/vuex
npm ERR! peer vuex@">=3.1.0" from @vuex-orm/core@0.36.4
npm ERR! node_modules/@vuex-orm/core
npm ERR! @vuex-orm/core@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by cuebit** [comment]
Can you verify the version of Vuex installed? Should be v3

**Comment by Pok09** [comment]
here is the info. from the package-lock.json file

[ ... ]
@nuxt/vue-app": {
      "version": "2.15.8",
      "resolved": "https://registry.npmjs.org/@nuxt/vue-app/-/vue-app-2.15.8.tgz",
      "requires": {
        "node-fetch": "^2.6.1",
        "ufo": "^0.7.4",
        "unfetch": "^4.2.0",
        "vue": "^2.6.12",
        "vue-client-only": "^2.0.0",
        "vue-meta": "^2.4.0",
        "vue-no-ssr": "^1.1.1",
        "vue-router": "^3.5.1",
        "vue-template-compiler": "^2.6.12",
        "vuex": "^3.6.2"
      }
[ ... ]

**Comment by Pok09** [comment]
> Can you verify the version of Vuex installed? Should be v3

here is the info. from the package-lock.json file

[ ... ]
@nuxt/vue-app": {
"version": "2.15.8",
"resolved": "https://registry.npmjs.org/@nuxt/vue-app/-/vue-app-2.15.8.tgz",
"requires": {
"node-fetch": "^2.6.1",
"ufo": "^0.7.4",
"unfetch": "^4.2.0",
"vue": "^2.6.12",
"vue-client-only": "^2.0.0",
"vue-meta": "^2.4.0",
"vue-no-ssr": "^1.1.1",
"vue-router": "^3.5.1",
"vue-template-compiler": "^2.6.12",
"vuex": "^3.6.2"
}
[ ... ]

**Comment by Drogwur** [comment]
You can try it - 
`"dependencies": {
    ...,
    "vuex": "<4"
  }`

In your package.json

**Comment by Pok09** [comment]
> You can try it - `"dependencies": { ..., "vuex": "<4" }`
> 
> In your package.json

Thank you very much, it works
