### ISSUE TITLE
Is there any way at all to use vuex-orm with Vue 3 (without @vue/compat)

### ISSUE THREAD

**Issue by vesper8** [revolver-app/vuex-orm#778]
I was surprised to not see anyone else ask this question anywhere.. I imagine this library is utterly incompatible with Vue 3.. but I just wanted to confirm my suspicion here.

Is it? And are there any plans on making this compatible with Vue 3? Is there a working fork maybe? This is such a useful project I find myself a bit dismayed if I can't use it in Vue 3.

**Comment by cuebit** [comment]
Suspicion and imagination have two very different meanings 😆 

Vuex ORM has no direct dependency on Vue; it merely depends on Vuex. Therefore, if there is a Vuex version compatible with Vue 3 (which there is), that would imply this library is compatible with Vue 3.

Have you tried the library without `@vue/compat`? Is there any particular concern limiting your ability to use Vuex ORM with Vue 3 without the compat bridge?

**Comment by vesper8** [comment]
Thank you for confirming that it works. I guess I'm still in my early days of migrating to Vue 3 and just didn't know how to couple it with my vuex store.. but I've tried it now and indeed everything seems to work fine!
