### ISSUE TITLE
Site is not available

### ISSUE THREAD

**Issue by koriooto** [revolver-app/vuex-orm#797]
Site is not available right now.

**Comment by cuebit** [comment]
Thanks. We're looking into it. 

/cc @kiaking

**Comment by WorthLMS** [comment]
Whew! SSL Error looks like cert probably expired :/ Hope it's fixed soon!

**Comment by WorthLMS** [comment]
Any idea on when this will be available?

**Comment by cuebit** [comment]
Soon. @kiaking is in control of the domain. It's 4am his time at the time of writing.

**Comment by WorthLMS** [comment]
Ah gratsi

Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Cue ***@***.***>
Sent: Tuesday, February 7, 2023 1:19:44 PM
To: vuex-orm/vuex-orm ***@***.***>
Cc: Software ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL]:Re: [vuex-orm/vuex-orm] Site is not available (Issue #797)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Soon. @kiaking<https://github.com/kiaking> is in control of the domain. It's 4am his time at the time of writing.

**Comment by koriooto** [comment]
@cuebit @kiaking hi, any updates?

**Comment by cuebit** [comment]
For the time being, you can view docs here: https://vuex-orm.netlify.app

**Comment by cuebit** [comment]
The official website is back up 👍
