### ISSUE TITLE
Looking for a way to return single model instance with relations

### ISSUE THREAD

**Issue by campgurus** [revolver-app/vuex-orm#798]
This may be an issue for documentation that I likely have missed. 

I have reviewed the docs and been able to call withAllRecursive to retrieve relations for a model object e.g.

Model.query().withAllRecursive().first();

However, instead of retrieving the "first" model object, I want to retrieve an instance by id and all relations to that object.

I was hoping for something like:

Model.query().whereId("33f56cff-a9a7-4919-b754-7dda5171ac77").withAllRecursive();

or

Model.query().withAllRecursive().whereId("33f56cff-a9a7-4919-b754-7dda5171ac77");

these don't throw errors, but return a Query object instead of data.

**Comment by cuebit** [comment]
`withAllRecursive` and its counterparts are relationship constraints. They don't invoke retrieval. You still need to invoke with `first()` for one or `get()` for many.

**Comment by cuebit** [comment]
Feel free to open a new issue if you encounter any more 👍
