### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by CinKon** [revolver-app/vuex-orm#9]
Either the documentation is wrong, or we can't find the correct way to create and mutate the store (https://revolver-app.gitbooks.io/vuex-orm/store/creating-and-updating.html).

TL;DR: Use `dispatch` instead of `commit`.

We tried to work with your commit approach, but always got the message: `[vuex] unknown mutation type: entities/user/create`

actions.js:
```javascript
export const setUserInfo = ({ commit }, val) => {
  commit('entities/user/create', { data: val })
}
```

component.vue:
```vue
<script>
  import { mapActions } from 'vuex'

  export default {
    methods: {
      ...mapActions(['setUserInfo']),
      async makeLogin () {
          const userData = { foo: 'bar' }

          this.setUserInfo(userData)
      }
    }
  }
</script>
```

models/user.js:
```javascript
// User Model
import Model from 'vuex-orm/lib/Model'

export default class User extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'user'

//  static primaryKey = 'id'

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields () {
    return {
      id: this.attr(null),
      gender: this.attr(''),
      username: this.attr(''),
      mailadress: this.attr(''),
      notification: this.attr(false),
      position: this.attr(''),
      avatar: this.attr(''),
      token: this.attr(null)
    }
  }
}
```

When we use `dispatch` in our `actions.js`, everything works just fine.

**Comment by kiaking** [comment]
Oh yes, the documentation is wrong. Thanks for the mention.

You want to use `dispatch` instead of `commit`. So the following should work.

```js
export const setUserInfo = ({ dispatch }, val) => {
  dispatch('entities/user/create', { data: val })
}
```

And for the side note, you can use `commit` (and `dispatch`) on root entities module. So the following will do the exactly same thing.

```js
export const setUserInfo = ({ commit }, val) => {
  commit('entities/create', { entity: 'user', data: val })
}

// or

export const setUserInfo = ({ dispatch }, val) => {
  dispatch('entities/create', { entity: 'user', data: val })
}
```

I'll fix the doc!

**Comment by CinKon** [comment]
For long-term: a working Demo would be great ;)
Maybe I'll commit one, when i have time...

**Comment by kiaking** [comment]
That would be super awesome! (I'll try to make one too...
